from __future__ import annotations

import enum

class MultipartState(enum.IntEnum):
    PREAMBLE = 0
    HEADER = 1
    BODY = 2
    END = 3

class PartBegin:
    @property
    def headers(self) -> list[tuple[bytes, bytes]]: ...

class PartData:
    @property
    def data(self) -> bytes: ...

class PartEnd: ...

class MultipartParser:
    state: MultipartState

    def __init__(
        self,
        boundary: bytes,
        *,
        max_size: int | None = None,
        max_header_count: int = 8,
        max_header_size: int = 4224,
    ) -> None: ...
    def feed(self, data: bytes) -> list[PartBegin | PartData | PartEnd]: ...
    def finish(self) -> None: ...

class MultipartBuilder:
    def __init__(self, *, boundary: bytes | None = None) -> None: ...
    @property
    def boundary(self) -> bytes: ...
    @property
    def content_type(self) -> str: ...
    def add_part(self, headers: list[tuple[bytes, bytes]], data: bytes) -> None: ...
    def add_field(self, name: str, value: bytes) -> None: ...
    def add_file(self, name: str, filename: str, data: bytes, *, content_type: str | None = None) -> None: ...
    def render_part(self, headers: list[tuple[bytes, bytes]]) -> bytes: ...
    def render_field(self, name: str) -> bytes: ...
    def render_file(self, name: str, filename: str, *, content_type: str | None = None) -> bytes: ...
    def closing(self) -> bytes: ...
    def build(self) -> bytes: ...

def parse_options_header(value: str) -> tuple[str, dict[str, str]]: ...
