from __future__ import annotations

import enum

class MultipartState(enum.IntEnum):
    PREAMBLE = 0
    HEADER = 1
    BODY = 2
    END = 3

class MultipartPart:
    class Header:
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> str: ...

    class Body:
        @property
        def data(self) -> bytes: ...
        @property
        def complete(self) -> bool: ...

class FormData:
    class File:
        @property
        def name(self) -> str: ...
        @property
        def filename(self) -> str: ...
        @property
        def content_type(self) -> str: ...
        @property
        def charset(self) -> str: ...
        @property
        def data(self) -> bytes: ...

    class Field:
        @property
        def name(self) -> str: ...
        @property
        def content_type(self) -> str: ...
        @property
        def charset(self) -> str: ...
        @property
        def data(self) -> bytes: ...

class MultipartParser:
    state: MultipartState

    def __init__(self, boundary: bytes, max_size: int | None = None, header_charset: str = "utf8") -> None: ...
    def parse(self, data: bytes) -> None: ...
    def next_part(self) -> FormData.Field | FormData.File | None: ...
    def next_event(self) -> MultipartPart.Header | MultipartPart.Body | None: ...
